routingRules:
  - domain: "nfh.global/testnet-deg"
    version: "2.0.0"
    targetType: "bpp"
    endpoints:
      - select
      - init
      - confirm
      - status
      - track
      - cancel
      - update
      - rate
      - support

  - domain: "nfh.global/testnet-deg"
    version: "2.0.0"
    targetType: "url"
    target:
      url: "https://34.14.221.66.sslip.io/beckn"
    endpoints:
      - discover

  - domain: "nfh.global/testnet-deg"
    version: "2.0.0"
    targetType: "url"
    target:
      url: "https://fabric.nfh.global/beckn/catalog/subscription"
      excludeAction: true
    endpoints:
      - subscribe
