routingRules:
  - domain: "nfh.global/testnet-deg"
    version: "2.0.0"
    targetType: "bpp"
    endpoints:
      - discover
      - publish
      - select
      - init
      - confirm
      - status
      - track
      - cancel
      - update
      - rate
      - support
